# Generated by Django 3.2.4 on 2021-06-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_descripcion_categorias_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='contenido',
        ),
    ]
