# Generated by Django 3.2.4 on 2021-06-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_descripcion_producto_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(upload_to='imagenes/'),
        ),
    ]
